name: aria2-oniondl

services:
  downloader:
    image: ghcr.io/neo2043/aria2-oniondl-downloader:main
    environment:
      - RPCPORT=6800
      - RPCSECRET=TEST123
      - TORSERVNUM=50
    volumes:
      - ./downloader/conf:/conf
      - ./downloader/log:/log
      - ./downloader/data:/data
    ports:
      - 6800:6800

  controller:
    image: ghcr.io/neo2043/aria2-oniondl-controller:main
    volumes:
      - ./controller/conf:/conf
      - ./controller/logs:/logs
    ports:
      - 7070:8080