FROM alpine:latest

LABEL maintainer="sn0b4ll"

COPY --chmod=777 www /var/www

COPY --chmod=777 run_nginx.sh /

COPY --chmod=777 conf /bak/conf

RUN apk add --update --no-cache bash nginx

# RUN wget https://github.com/mayswind/AriaNg-DailyBuild/archive/master.zip

CMD ["/run_nginx.sh"]

